- hosts: fedora_clients
  become: yes
  tasks:
  - name: Check if the python-libdnf5 module is available
    package:
      name:
      - python-libdnf5
      state: present
    ignore_errors: true
    register: need_manual_package
  
  - name: Install python-libdnf5
    command: dnf install -y python-libdnf5
    when: need_manual_package.failed|default(false) == true

  - name: Ensure selinux works with CIFS dirs
    command: setsebool -P use_samba_home_dirs 1

  # There's an alert about polyinstantiation which is probably just a bug due to pam_mount overmounting .cache

  - name: Install pre-requisite packages
    package:
      name:
      - krb5-workstation
      - gdm
      - sssd-tools
      - tlog

  - name: Remove lightdm
    package:
      name:
      - slick-greeter
      - slick-greeter-cinnamon
      - lightdm
      - lightdm-settings
      - lightdm-gobject
      state: absent

  - name: Disable systemd-home
    service:
      name: systemd-homed
      state: stopped
      enabled: false

  # check for realm membership

  # join realm

# THIS: THIS IS HOW YOU GET HOME DIRECTORIES TO WORK. USE PAM_MOUNT.
# <volume sgrp="domain users@default.libvirt"
#     fstype="cifs"
#     server="server-1.default.libvirt"
#     path="Users$/%(USER)"
#     mountpoint="/home/%(USER)"
#     options="sec=krb5i,cruid=%(USERUID),vers=3.0"
# />

  - name: Ensure a /usr/local/sbin dir exists
    file:
      path: /usr/local/sbin
      state: directory
      mode: "0755"
      owner: root
      group: root

  - name: Configure SELinux
    command: "{{item}}"
    loop:
    - semanage fcontext -a -t root_t /usr/local/sbin
    - restorecon -v /usr/local/sbin

  - name: Install the local home directories script
    copy:
      src: files/usr/local/sbin/create-local-homedir.sh
      dest: /usr/local/sbin/create-local-homedir.sh
      mode: "0755"
      owner: root
      group: root

  - name: Install the local home directories script for GDM
    copy:
      src: files/usr/local/sbin/create-local-homedir.sh
      dest: /usr/local/sbin/create-local-homedir-gdm.sh
      mode: "0755"
      owner: root
      group: root

  - name: Configure SELinux
    command: "{{item}}"
    loop:
    - semanage fcontext -a -t xdm_unconfined_exec_t /usr/local/sbin/create-local-homedir-gdm.sh
    - restorecon -v /usr/local/sbin/create-local-homedir-gdm.sh

  - name: Check if custom profile exists
    command: authselect show custom/sssd-ext
    failed_when: false
    register: authselect_result

  - name: Setup an extended sssd authselect profile
    command: authselect create-profile -b sssd --symlink-nsswitch --symlink-dconf sssd-ext
    when: authselect_result.rc != 0

  - name: Edit the profile
    copy:
      src: files/authselect/sssd-ext/{{item}}
      dest: /etc/authselect/custom/sssd-ext/{{item}}
      mode: "0644"
      owner: root
      group: root
    loop:
    - fingerprint-auth 
    - password-auth
    - postlogin
    - README
    - REQUIREMENTS
    - smartcard-auth
    - system-auth

  - name: Enable mmap on files by domains
    command: setsebool -P domain_can_mmap_files 1

  - name: Enable polyinstantiation
    command: setsebool -P polyinstantiation_enabled 1

  - name: Write an SELinux policy extension for the startup system
    copy:
      content: |
        module my-local 1.0;

        require {
          type systemd_logind_inhibit_var_run_t;
          type proc_t;
          type xdm_t;
          class filesystem associate;
          class dir { add_name write };
          class fifo_file getattr;
        }

        #============= xdm_t ==============
        allow xdm_t proc_t:filesystem associate;
        allow xdm_t self:dir { add_name write };
        allow xdm_t systemd_logind_inhibit_var_run_t:fifo_file getattr;
      dest: /root/my-local.te
      owner: root
      group: root
      mode: "0600"

  - name: Compile and install the module
    command: "{{item}}"
    loop:
    - /bin/bash -c 'semodule -r my-local || /bin/true'
    - checkmodule -M -m -o my-local.mod my-local.te
    - semodule_package -o my-local.pp -m my-local.mod
    - semodule -X 300 -i my-local.pp

  - name: Ensure cache directory exists
    file:
      path: /var/cache/user
      owner: root
      group: root
      mode: "0755"
      state: directory

  - name: Configure SELinux contexts for altered cache location 
    command: "{{item}}"
    loop:
    - semanage fcontext -a -t cache_home_t /var/cache/user
    - restorecon -v /var/cache/user

  - name: Remap XDG_CACHE_HOME
    lineinfile:
      path: /etc/security/pam_env.conf
      regexp: "^XDG_CACHE_HOME.*"
      line: "XDG_CACHE_HOME\tDEFAULT=\"/var/cache/user/${USER}\""
      state: present

  - name: Configure /etc/environment globally
    lineinfile:
      path: /etc/environment
      regexp: "^REQUESTS_CA_BUNDLE.*"
      line: REQUESTS_CA_BUNDLE=/etc/pki/tls/certs/ca-certificates.crt

  - name: Ensure pam-mount is installed
    package:
      name: pam_mount
      state: present

  - name: Configure pam_mount
    blockinfile:
      path: /etc/security/pam_mount.conf.xml
      insertafter: "\\s*<!--\\s*Volume definitions.*"
      marker: <!-- {mark} ANSIBLE MANAGED BLOCK -->
      block: |
        <volume sgrp="domain users"
            fstype="cifs"
            server="server-1.{{ad.domain_name}}"
            path="Users$/%(USER)"
            mountpoint="/home/%(USER)"
            options="sec=krb5i,cruid=%(USERUID),vers=default,nobrl,mfsymlinks,cifsacl,context=unconfined_u:object_r:user_home_t:s0"
        />

  # https://bugs.launchpad.net/ubuntu/+source/cifs-utils/+bug/1764778
  - name: Configure dconf to work over CIFS
    lineinfile:
      path: /etc/dconf/profile/user
      insertbefore: BOF
      line: service-db:keyfile/user

  - name: Enable the new profile
    command: >-
      authselect select custom/sssd-ext 
        with-libvirt
        with-pam-mount
        with-pam-exec-homedir
        with-pam-gnome-keyring
        with-smartcard
        with-subid
        with-tlog
        with-sudo
  
  - name: Ensure profile is active
    command: authselect apply-changes

  - name: Configure sssd
    lineinfile:
      path: /etc/sssd/sssd.conf
      regexp: ^services = .*
      line: services = nss, pam, ssh, sudo
      insertafter: "^\\[sssd\\]"
    notify: restart sssd

  - name: Configure sssd
    lineinfile:
      path: /etc/sssd/sssd.conf
      regexp: ^use_fully_qualified_names = .*
      line: use_fully_qualified_names = False
    notify: restart sssd

  - name: Configure sssd fallback_homedir
    lineinfile:
      path: /etc/sssd/sssd.conf
      regexp: ^fallback_homedir = .*
      line: fallback_homedir = /home/%u
    notify: restart sssd

  - name: Configure sssd
    lineinfile:
      path: /etc/sssd/sssd.conf
      line: "[pam]"
    notify: restart sssd

  - name: Configure sssd
    lineinfile:
      path: /etc/sssd/sssd.conf
      insertafter: "\\[pam\\]"
      line: pam_cert_auth = True
    notify: restart sssd

  - name: Configure SSH server to use SSSD authorized keys
    copy:
      content: |
        # Site Configuration to use SSSD for known hosts
        AuthorizedKeysCommand /usr/bin/sss_ssh_authorizedkeys
      dest: /etc/ssh/ssh_config.d/90-site.conf
      owner: root
      group: root
      mode: "0644"
    notify: restart sshd

  - name: Configure pam_sss_knownhosts
    copy:
      content: |
        # Site Configuration to use SSSD for known hosts
        GlobalKnownHostsFile /var/lib/sss/pubconf/known_hosts
        ProxyCommand /usr/bin/sss_ssh_knownhostsproxy -p %p %h
      dest: /etc/ssh/ssh_config.d/90-site.conf
      owner: root
      group: root
      mode: "0644"

  - name: Fix csd-color
    command: glib-compile-schemas --targetdir /usr/share/glib-2.0/schemas/ /usr/share/glib-2.0/schemas

  - name: Configure pam_group
    lineinfile:
      path: /etc/security/group.conf
      line: "*;*;%domain users;Al0000-2400;render,audio,video,dialout,colord"

  - name: Configure libsecret integration with keepassxc
    lineinfile:
      path: /usr/share/dbus-1/services/org.gnome.keyring.service
      regexp: Exec=.*
      line: Exec=/usr/local/sbin/keepassxc-gnome-wrapper

  - name: Configure libsecret integration with keepassxc
    lineinfile:
      path: /usr/share/dbus-1/services/org.freedesktop.secrets.service
      regexp: Exec=.*
      line: Exec=/usr/local/sbin/keepassxc-gnome-wrapper

  - name: Configure libsecret integration with keepassxc
    lineinfile:
      path: /usr/share/dbus-1/services/org.freedesktop.impl.portal.Secret.service
      regexp: Exec=.*
      line: Exec=/usr/local/sbin/keepassxc-gnome-wrapper

  - name: Copy wrapper script for the keepassxc start
    copy:
      content: |
        #!/bin/bash
        opt_daemonize=0
        while [ -n "$1" ]; do
          case "$1" in
            --daemonize)
              opt_daemonize=1
              ;;
            *)
            break
          esac
        done

        if [ $opt_daemonize = 1 ]; then
          exec /usr/sbin/keepassxc --minimized --pw-stdin ${HOME}/.login.kdbx
        else
          exec /usr/sbin/keepassxc --minimized ${HOME}/.login.kdbx
        fi
      dest: /usr/local/sbin/keepassxc-gnome-wrapper
      owner: root
      group: root
      mode: "0755"

  - name: Replace gnome-keyring-daemon with the script
    file:
      src: /usr/local/sbin/keepassxc-gnome-wrapper
      dest: /usr/bin/gnome-keyring-daemon
      owner: root
      group: root
      mode: "0755"
      force: true
      state: link

  # TODO: Replace gnome-keyring with keepassxc
  # See the  to fix the launch.
  # 
  # 

# .config/keepassxc/keepassxc.ini
# [General]
# BackupBeforeSave=true
# ConfigVersion=2
# MinimizeAfterUnlock=true

# [Browser]
# CustomProxyLocation=

# [FdoSecrets]
# Enabled=true

# [GUI]
# MinimizeOnStartup=true
# MinimizeToTray=true
# ShowTrayIcon=true
# TrayIconAppearance=colorful

# [KeeShare]
# Active="<?xml version=\"1.0\"?><KeeShare><Active/></KeeShare>\n"
# Own="<?xml version=\"1.0\"?><KeeShare><PrivateKey>MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQClN69eH0maBUm0LF8MN+KNtdwrncVHraD6HH6ymVrjC+0Fno17a+SjS8hkETEIw0uYIy/xB+W5OAxR8jE9htKzu6ykYEF2zFxkL/k4Iwe/OCs+IL1rKObhE77gzR4zNBmGVqfWI3JuSR4xRcGgpOrLlE74DyvHFSrT00OvJ2m3V/U8kEDQzb4PbXupu+7NjCY0QrOI6w+J/6HpE3GNqmHij/2Wc/vNkVmkMmW4YAnfdr6PTkWQ6yIoDWIru3LuUC1+2FZ9xheodLHbLUa86Y13aHSiX52oz6WplBqWNm2WmqRJxV7kLwgvKQbNR0PiF7kozdz703VNinCPANEtNBZDAgMBAAECggEAAVeAmdSzr7bArioWwXArglcw3m0PKkyQCoRqZNOf3J5OoeyNARjLA9+QaSD5gN+jTX+ko0ntpyxF+BjlTlkBHEsh3xFDrqpp+zwNzBIErEcKSyIiNCKsKP+O+j6+zFggejssW9ibHoVbH1zD+D5I83BWerzBVqFvQa/MdT9R3RxIp1uJ0oCWyfSa36hJU0erAyGCm+6KnsUkzq+CtIpu6ARiJ17Z0OTniOYjBRWkKvglFcdQVVKyBxRzSpAcstxyDEKN1ZzI9eW2AhakVR9yd0DyI0hIcODCM8VFnmxVXwvQDqjiGX0y6eQyj6I6oixUgirxE65jR/jKmvrwZpkgmQKBgQDX9PQRAg3gFo2B3wIKcNCyUUOEvFwptHkAIBzNGR+9d6PipGoT+CwzkhjwxAIbgcs3fEU0GoNm5I0OyUdKfPTUb0Ruisr8iSiF9JfPJTVQnXgxHfl9hIEewwZ5+NUDV7Mq56w3/h0wxwIvTpKnOk74T7CFPNO6NqXE1O4q/KBqCwKBgQDD2jxLxRptemdSwfx+XT+ci57BYmu2tvK03u4Nrum+xElWQsJ0qBPmDTviqMr4D3aVeIrcXeus1fDrSl8YBcC6I8W18bXXy3C/29FscLe7nR88xn2R22b9wZAYm+K+5re5AfbtJFh6mDjhNM0IzFhKHlhY5Q4zEDBZbh3ezFxfqQKBgHs5PyaRSH+L/tSS/iQc+Ug2TFNp8yCs5LoomKaC5nSC1tWUwR6B5h7LB0YiYZ12cxFG7GntkvrcAIzmVrJvGHg6wQ5eTbLJRIEi7ph4/7HvGEzWcKypNc/qskBYtpsAqLAbn04Xxmo1s85whAe9op/XQL7V1W4UjoQAh6GpopK/AoGBAID9S7bvgr9V3ZUA1CX5jjqxLgbZpm15QpJjPM/gQmx05IQehenFBQ3/61AVsU/9BzHcaUBHzz9OzFR67/RnXY56nu182zHb+E80HFLaTfgPvJIPfIZCxSsdf6TljkoCtD/yDkoTJP7hIJ0aZGuGAiQWpkMt4NM6t00/HAcv+yq5AoGBAJFMmpgkFb27BtIP4x4e7aLGIwbVDsWeHTBjD4nuQmyyNQ7arPitunHYEvcRFrtLJpw1fWwJSHg/o5N0L/XTHuMt07PNm2gPy/rd93FiUMbT1ERYqMArEco/PX9jIOWJRDtmyJ43aeTPDTwHhvae1h1PxT99QgXKIGTKunoZFLV1</PrivateKey><PublicKey><Signer>john.everyman</Signer><Key>MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQClN69eH0maBUm0LF8MN+KNtdwrncVHraD6HH6ymVrjC+0Fno17a+SjS8hkETEIw0uYIy/xB+W5OAxR8jE9htKzu6ykYEF2zFxkL/k4Iwe/OCs+IL1rKObhE77gzR4zNBmGVqfWI3JuSR4xRcGgpOrLlE74DyvHFSrT00OvJ2m3V/U8kEDQzb4PbXupu+7NjCY0QrOI6w+J/6HpE3GNqmHij/2Wc/vNkVmkMmW4YAnfdr6PTkWQ6yIoDWIru3LuUC1+2FZ9xheodLHbLUa86Y13aHSiX52oz6WplBqWNm2WmqRJxV7kLwgvKQbNR0PiF7kozdz703VNinCPANEtNBZDAgMBAAECggEAAVeAmdSzr7bArioWwXArglcw3m0PKkyQCoRqZNOf3J5OoeyNARjLA9+QaSD5gN+jTX+ko0ntpyxF+BjlTlkBHEsh3xFDrqpp+zwNzBIErEcKSyIiNCKsKP+O+j6+zFggejssW9ibHoVbH1zD+D5I83BWerzBVqFvQa/MdT9R3RxIp1uJ0oCWyfSa36hJU0erAyGCm+6KnsUkzq+CtIpu6ARiJ17Z0OTniOYjBRWkKvglFcdQVVKyBxRzSpAcstxyDEKN1ZzI9eW2AhakVR9yd0DyI0hIcODCM8VFnmxVXwvQDqjiGX0y6eQyj6I6oixUgirxE65jR/jKmvrwZpkgmQKBgQDX9PQRAg3gFo2B3wIKcNCyUUOEvFwptHkAIBzNGR+9d6PipGoT+CwzkhjwxAIbgcs3fEU0GoNm5I0OyUdKfPTUb0Ruisr8iSiF9JfPJTVQnXgxHfl9hIEewwZ5+NUDV7Mq56w3/h0wxwIvTpKnOk74T7CFPNO6NqXE1O4q/KBqCwKBgQDD2jxLxRptemdSwfx+XT+ci57BYmu2tvK03u4Nrum+xElWQsJ0qBPmDTviqMr4D3aVeIrcXeus1fDrSl8YBcC6I8W18bXXy3C/29FscLe7nR88xn2R22b9wZAYm+K+5re5AfbtJFh6mDjhNM0IzFhKHlhY5Q4zEDBZbh3ezFxfqQKBgHs5PyaRSH+L/tSS/iQc+Ug2TFNp8yCs5LoomKaC5nSC1tWUwR6B5h7LB0YiYZ12cxFG7GntkvrcAIzmVrJvGHg6wQ5eTbLJRIEi7ph4/7HvGEzWcKypNc/qskBYtpsAqLAbn04Xxmo1s85whAe9op/XQL7V1W4UjoQAh6GpopK/AoGBAID9S7bvgr9V3ZUA1CX5jjqxLgbZpm15QpJjPM/gQmx05IQehenFBQ3/61AVsU/9BzHcaUBHzz9OzFR67/RnXY56nu182zHb+E80HFLaTfgPvJIPfIZCxSsdf6TljkoCtD/yDkoTJP7hIJ0aZGuGAiQWpkMt4NM6t00/HAcv+yq5AoGBAJFMmpgkFb27BtIP4x4e7aLGIwbVDsWeHTBjD4nuQmyyNQ7arPitunHYEvcRFrtLJpw1fWwJSHg/o5N0L/XTHuMt07PNm2gPy/rd93FiUMbT1ERYqMArEco/PX9jIOWJRDtmyJ43aeTPDTwHhvae1h1PxT99QgXKIGTKunoZFLV1</Key></PublicKey></KeeShare>\n"
# QuietSuccess=true

# [PasswordGenerator]
# AdditionalChars=
# ExcludedChars=

# [SSHAgent]
# Enabled=true

  # [session_recording]
  # TODO
  handlers:
  - name: restart oddjobd
    service:
      name: oddjobd
      state: restarted

  - name: restart sshd
    service:
      name: sshd
      state: restarted
  - name: restart sssd
    service:
      name: sssd
      state: restarted