- hosts: ad_servers
  #become: yes
  tasks:
  # A gMSA requires a KDS root key to be created. This key must be valid for
  # 10 hours before it can be used. This example creates the key and sets the
  # time for 10 hours ago to let it be used immediately. If your environment
  # uses multiple DCs you will still need to wait 10 hours for replication to
  # occur or target the DC you created the key on. Required Domain Admin or
  # Enterprise Admin privileges.
  - name: Create KDS root key if not present
    ansible.windows.win_powershell:
      error_action: stop
      script: |
        $Ansible.Changed = $false
        if (-not (Get-KdsRootKey)) {
            Add-KdsRootKey -EffectiveTime ((Get-Date).AddHours(-10))
            $Ansible.Changed = $true
        }

  - name: Ensure users exist
    microsoft.ad.service_account:
      identity:: "{{item.key}}"
      state: present
      display_name: "{{item.value.details.display_name}}"
      allowed_to_retrieve_password:
        set:
          - Domain Admins
      # attributes: 
      #   set: |-
      #     {%- set attrs = item.value.details.attributes|default({}) -%}
      #     {%- do attrs.update({"profilePath": [ad_dirs.homeServer, ad_dirs.serviceAccountProfiles | win_basename, item.key + "@" + ad.domain_name] | join("\\") }) -%}
      #     {%- do attrs.update({"homeDirectory": [ad_dirs.homeServer, ad_dirs.serviceAccountHomes | win_basename, item.key + "@" + ad.domain_name] | join("\\") }) -%}
      #     {%- do attrs.update({"homeDrive": ad_dirs.homeDrive }) -%}
      #     {{ attrs }}
    loop: "{{ad_service_accounts|dict2items}}"