---
# Add the sudo schema
- hosts: ad-servers
  run_once:
  tasks:
  - name: Copy sudo schema to guest
    win_copy:
      src: '{{ item }}.schema'
      dest: 'C:\{{ item }}.schema'
    with_items:
    - sudo

  - name: Install additional schemas
    win_shell: >-
      ldifde -i -f C:\{{ item }}.schema -c DC=X {{ ad_dc }} 
      -b "{{ ad.domain_admin_username }}" "{{ ad.domain_name }}" "{{ ad.domain_admin_password }}"
    register: schema
    failed_when: schema.rc != 0 and schema.stdout is not search('ENTRY_EXISTS')
    changed_when: schema.rc == 0
    with_items:
    - sudo