- hosts: ad-servers
  #become: yes
  tasks:
  - name: Ensure users exist
    microsoft.ad.user:
      identity: "{{item.key}}"
      password: "{{item.value.password}}"
      state: present
      groups: 
        set: "{{item.value.groups}}"
      # Extras
      firstname: "{{item.value.details.firstname}}"
      surname: "{{item.value.details.surname}}"
      display_name: "{{item.value.details.display_name}}"
      company: "{{item.value.details.company}}"
      street: "{{item.value.details.street}}"
      city: "{{item.value.details.city}}"
      postal_code: "{{item.value.details.postal_code}}"
      country: "{{item.value.details.country}}"
      email: "{{item.value.details.email}}"
      attributes: 
        set: |-
          {%- set attrs = item.value.details.attributes -%}
          {%- do attrs.update({"profilePath": [ad_dirs.homeServer, ad_dirs.profiles | win_basename, item.key + "@" + ad.domain_name] | join("\\") }) -%}
          {%- do attrs.update({"homeDirectory": [ad_dirs.homeServer, ad_dirs.homes | win_basename, item.key + "@" + ad.domain_name] | join("\\") }) -%}
          {%- do attrs.update({"homeDrive": ad_dirs.homeDrive }) -%}
          {{ attrs }}
    loop: "{{ad_users|dict2items}}"

  - name: Ensure user home folders exist
    ansible.windows.win_file:
      path: "{{ ad_dirs.homes }}\\{{ item.key }}@{{ ad.domain_name }}"
      state: directory
    loop: "{{ad_users|dict2items}}"

  - name: Ensure correct permissions on user home folders
    ansible.windows.win_acl:
      path: "{{ ad_dirs.homes }}\\{{ item.key }}@{{ ad.domain_name }}"
      user: "{{ item.key }}@{{ ad.domain_name }}"
      type: allow
      state: present
      rights: FullControl
      # propagation: NoPropagateInherit
      # inherit: None
    loop: "{{ad_users|dict2items}}"