---
# Set basic policy objects for Linux
- hosts: ad-servers
  run_once: true
  tasks:
  - name: sudoer defaults
    microsoft.ad.object:
      name: defaults
      path: OU=sudoers,{{ ad_dc }}
      description: Default SUDO options
      type: sudoRole
      attributes:
        set:
          sudoOption: 
          - env_keep+=SSH_AUTH_SOCK
      state: present

  - name: NOPASSWD sudo for desktop admins
    microsoft.ad.object:
      name: desktop_admins_sudo
      path: OU=sudoers,{{ ad_dc }}
      description: Desktop Administrators
      type: sudoRole
      attributes:
        set:
          sudoUser: "%desktop admins@default.libvirt"
          sudoHost: ALL
          sudoCommand: ALL
          sudoOption:
          # Note: this is the option which replaced how nopasswd would be done.
          - "!authenticate"
      state: present