---
# Add the sudo schema
- hosts: ad_servers
  run_once: true
  tasks:
  - name: Copy sudo schema to guest
    win_copy:
      src: '{{ item }}.schema'
      dest: 'C:\{{ item }}.schema'
    with_items:
    - sudo

  - name: Install additional schemas
    win_shell: >-
      ldifde -i -f C:\{{ item }}.schema -c DC=X {{ ad_dc }} 
      -b "{{ ad.domain_admin_username }}" "{{ ad.domain_name }}" "{{ ad.domain_admin_password }}"
    register: schema
    failed_when: schema.rc != 0 and schema.stdout is not search('ENTRY_EXISTS')
    changed_when: schema.rc == 0
    with_items:
    - sudo

- hosts: ad_servers
  run_once: true
  tasks:
  - name: Add the sudo OU
    microsoft.ad.ou:
      name: sudoers
      path: "{{ad_dc}}"
      state: present
      protect_from_deletion: true

  - name: Add the autofs OU
    microsoft.ad.ou:
      name: autofs
      path: "{{ad_dc}}"
      state: present
      protect_from_deletion: true