ansible_user: Administrator@{{ad.domain_name|upper}}
ansible_password: "{{ad.domain_admin_password}}"
ansible_winrm_transport: kerberos
ansible_winrm_kinit_cmd: "{{playbook_dir}}/kinit.sh"
ansible_winrm_kerberos_delegation: true

# TODO: something clever with downloading certificates